### ISSUE TITLE
[Question] Ambiguous column names

### ISSUE THREAD

**Issue by 3amprogrammer** [drawmyattention/advanced-eloquent-search-filters#3]
I really like your solution, but I don't see it working with complex queries. Let's say I join roles table. Roles table has a name column. Users table also has a name column.

**Comment by amochohan** [comment]
I've solved this by prefixing the table name before the column being searched.

For example:

    return $q->where('countries.name', 'LIKE', '%'.$value.'%');

Or if you'd prefer to keep table names dynamic:

    return $q->where((new Country())->getTable().'.name', 'LIKE', '%'.$value.'%');
