### ISSUE TITLE
Eloquent-Builder package,Inspired by this repository

### ISSUE THREAD

**Issue by mohammad-fouladgar** [drawmyattention/advanced-eloquent-search-filters#4]
Hello everyone, especially @amochohan 

I have read your article titled **'Writing advanced Eloquent search query filters' on the 'Medium'** site. It was very useful and inspired me to write a package for **Laravel** framework based on your article. It would be a pleasure to know what you think about the package. Thank you.

https://github.com/mohammad-fouladgar/eloquent-builder

**Comment by anjing-go** [comment]
Hi  If you add a field that does not exist in the database table   
for example posts table no have name column but you created a  class Name implements Filter
It will be reported wrong.
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'where clause' `

Apart from this problem, this solution is really elegant.Thank you for the idea.

**Comment by mohammad-fouladgar** [comment]
Hi @langhack 
Thank you for note. You are right.
Can you open a issue as a problem in [here](https://github.com/mohammad-fouladgar/eloquent-builder/issues)?
